# Generated by Django 3.2.4 on 2021-07-15 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='books',
            name='bookFile',
        ),
        migrations.AddField(
            model_name='books',
            name='coverImage',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
