# Generated by Django 3.2.4 on 2021-07-15 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_auto_20210715_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='bookFile',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
